### ISSUE TITLE
wrong output with string.sub and ==

### ISSUE THREAD

**Issue by vParkuu** [TheGreatSageEqualToHeaven/Fiu#5]
![image](https://github.com/TheGreatSageEqualToHeaven/Fiu/assets/92997274/acfc65a7-e189-4a7b-8a65-6028c386b2c3)
![image](https://github.com/TheGreatSageEqualToHeaven/Fiu/assets/92997274/8c218d45-43bc-4c40-b957-ac82c7b8ce40)
the output without - Fiu:481 is roblox studio's command bar returning the correct output
Fiu returns the wrong output

**Comment by TheGreatSageEqualToHeaven** [comment]
Sorry for the late respose, I've been on holiday and rather busy recently. I'll get to fixing all the bugs Fiu has in February unless someone pr's in a fix before then. (hint hint)

**Comment by TheGreatSageEqualToHeaven** [comment]
This is fixed in the latest commit.
